# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_img_zoom_Layout5.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fileButton = QtWidgets.QPushButton(self.centralwidget)
        self.fileButton.setMinimumSize(QtCore.QSize(94, 32))
        self.fileButton.setMaximumSize(QtCore.QSize(16777215, 32))
        self.fileButton.setObjectName("fileButton")
        self.horizontalLayout_2.addWidget(self.fileButton)
        self.show_file_path = QtWidgets.QTextEdit(self.centralwidget)
        self.show_file_path.setMinimumSize(QtCore.QSize(300, 30))
        self.show_file_path.setMaximumSize(QtCore.QSize(16777215, 32))
        self.show_file_path.setObjectName("show_file_path")
        self.horizontalLayout_2.addWidget(self.show_file_path)
        self.btn_prt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_prt.setMinimumSize(QtCore.QSize(95, 32))
        self.btn_prt.setMaximumSize(QtCore.QSize(16777215, 32))
        self.btn_prt.setObjectName("btn_prt")
        self.horizontalLayout_2.addWidget(self.btn_prt)
        self.btn_next = QtWidgets.QPushButton(self.centralwidget)
        self.btn_next.setMinimumSize(QtCore.QSize(95, 32))
        self.btn_next.setMaximumSize(QtCore.QSize(16777215, 32))
        self.btn_next.setObjectName("btn_next")
        self.horizontalLayout_2.addWidget(self.btn_next)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        # self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        # self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 772, 229))
        # self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        # self.label_img = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_img = QtWidgets.QLabel()
        self.label_img.setGeometry(QtCore.QRect(0, 0, 711, 461))
        self.label_img.setMinimumSize(QtCore.QSize(400, 300))
        self.label_img.setObjectName("label_img")
        self.scrollArea.setWidget(self.label_img)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_zoom_in = QtWidgets.QPushButton(self.centralwidget)
        self.btn_zoom_in.setMinimumSize(QtCore.QSize(90, 32))
        self.btn_zoom_in.setMaximumSize(QtCore.QSize(16777215, 32))
        self.btn_zoom_in.setObjectName("btn_zoom_in")
        self.horizontalLayout_3.addWidget(self.btn_zoom_in)
        self.btn_zoom_out = QtWidgets.QPushButton(self.centralwidget)
        self.btn_zoom_out.setMinimumSize(QtCore.QSize(90, 32))
        self.btn_zoom_out.setMaximumSize(QtCore.QSize(16777215, 32))
        self.btn_zoom_out.setObjectName("btn_zoom_out")
        self.horizontalLayout_3.addWidget(self.btn_zoom_out)
        self.lab_bar = QtWidgets.QLabel(self.centralwidget)
        self.lab_bar.setMinimumSize(QtCore.QSize(90, 32))
        self.lab_bar.setMaximumSize(QtCore.QSize(16777215, 32))
        self.lab_bar.setObjectName("lab_bar")
        self.horizontalLayout_3.addWidget(self.lab_bar)
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setMinimumSize(QtCore.QSize(300, 32))
        self.horizontalSlider.setMaximumSize(QtCore.QSize(16777215, 32))
        self.horizontalSlider.setMaximum(255)
        self.horizontalSlider.setProperty("value", 100)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_3.addWidget(self.horizontalSlider)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CELL COUNT"))
        self.fileButton.setText(_translate("MainWindow", "載入圖片"))
        self.btn_prt.setText(_translate("MainWindow", "Previous"))
        self.btn_next.setText(_translate("MainWindow", "Next"))
        self.label_img.setText(_translate("MainWindow", "img"))
        self.btn_zoom_in.setText(_translate("MainWindow", "zoom in"))
        self.btn_zoom_out.setText(_translate("MainWindow", "zoom out"))
        self.lab_bar.setText(_translate("MainWindow", "0x0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
